### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by salutis**
Thank you for an amazing textbook. I have learned a lot from it.

### CODE REVIEW

**Comment by salutis** [comment]
@oscarlevin Can we merge this?

**Comment by oscarlevin** [comment]
Thank you for the contribution.  I want to go through each of these carefully (as they might change page breaks at the very least) but likely will not be able to until the Fall semester ends.

**Comment by salutis** [comment]
@oscarlevin That makes sense; I will leave the PR open then. Thank you!

**Comment by oscarlevin** [comment]
Thanks for the contribution.

**Pull request merged**
